# Site settings
title: 谭学诚的文章
user_name: 谭学诚
email: tanxuecheng@outlook.com
description: ""
baseurl: ""
url: "http://TanXuecheng.github.io"
github_username:  TanXuecheng

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title.html

paginate: 5
paginate_path: "blog/page:num"
